config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'authorizations/authorize'
      post 'authorizations/request_token'
      get 'authorizations/fail'
      get 'users/me'
      get 'users/profile'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index'

  resources :users, only: [:new, :create]
  resources :main, only: [:index]
  resource :profile
  resources :websites

  get 'regenerate_secrets/:id', to: 'websites#regenerate_secrets', as: 'secrets'

  controller :sessions do
    get 'login', to: 'sessions#new'
    post 'sessions', to: 'sessions#create'
    get 'logout', to: 'sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/granted_access.rb
class GrantedAccess < ApplicationRecord
  belongs_to :user
  belongs_to :website

  before_create :generate_tokens

  def generate_tokens
    self.code = SecureRandom.hex(16)
    self.access_token = SecureRandom.hex(16)
    self.refresh_token = SecureRandom.hex(16)
    self.access_token_expires_at = Time.now + 6.hours
  end

  def self.try_authenticate(token)
    access = self.find_by_access_token(token)
    access&.user
  end

  def refresh_access_token
    self.access_token = SecureRandom.hex(16)
    self.access_token_expires_at = Time.now + 6.hours
    self.save
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  belongs_to :user

  validates :first_name, :last_name, :gender, :birth_date, :street, :city, :country, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  has_many :websites, dependent: :destroy
  has_many :granted_accesses, dependent: :destroy

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  has_secure_password
  has_secure_token

  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL }

  def self.try_authenticate(email, password)
    self.find_by_email(email).try(:authenticate, password)
  end
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :user
  has_many :granted_accesses, dependent: :destroy

  has_secure_token :secrete_token

  before_create :create_secure_id

  validates :name, :domain_name, presence: true

  def create_secure_id
    self.secrete_id = SecureRandom.uuid
  end

  def self.try_authenticate(id, token)
    site = self.find_by_secrete_id(id)
    real_token = site.try(:secrete_token)
    real_token == token ? site : nil
  end
end

app/controllers/api/v1/authorizations_controller.rb
class Api::V1::AuthorizationsController < ApplicationController
  skip_before_action :authenticate_user, only: [:request_token, :fail]
  skip_before_action :verify_authenticity_token

  def authorize
    auth = Authorization.new(current_user, authorization_params)
    redirect_to auth.response_url
  end

  def request_token
    website = Website.try_authenticate(params[:client_id], params[:client_secret])
    if params[:grant_type] == 'authorization_code'
      current_access = website&.granted_accesses&.find_by_code(params[:code])
    elsif params[:grant_type] == 'refresh_token'
      current_access = website&.granted_accesses&.find_by_refresh_token(params[:refresh_token])
      current_access&.refresh_access_token
    end
    if current_access
      render json: { access_token: current_access.access_token,
                     refresh_token: current_access.refresh_token,
                     expires_at: current_access.access_token_expires_at.to_i },
             status: 200
    else
      render json: { error: 'Authentication failed on token request' }, status: 401
    end
  end

  def fail
    render json: { error: 'Authentication by token failed' }, status: 401
  end

  private

  def authorization_params
    params.permit(:client_id, :state, :redirect_uri, :response_type)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :authenticate_user
  before_action :authenticate_api_user, :set_user

  def me
    respond_to do |format|
      format.json
    end
  end

  def profile
    respond_to do |format|
      format.json
    end
  end

  private

  def authenticate_api_user
    authenticate!(scope: :api_user)
  end

  def set_user
    @user = current_user(:api_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user

  private

  def authenticate_user
    unless authenticated?
      session[:original_request] = request.original_url
      flash[:warning] = 'You have to login before proceed!'
      redirect_to login_path
    end
  end
end

app/controllers/concerns/authorization.rb
class Authorization
  def initialize(user, params)
    @user = user
    @params_hash = params
  end

  def response_url
    website = Website.find_by_secrete_id(@params_hash[:client_id])
    if website
      grant = @user.granted_accesses.where(website_id: website.id).first_or_initialize
      grant.state = @params_hash[:state]
      if grant.save
        new_params = { code: grant.code,
                       response_type: 'code',
                       state: grant.state }
      end
    else
      new_params = { state: @params_hash[:state] }
    end

    uri = URI.parse(@params_hash[:redirect_uri])
    URI::HTTP.build([nil, uri.host, uri.port, uri.path, new_params.to_query, nil]).to_s
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @profile.update_attributes(profile_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def destroy
    @profile.destroy
    redirect_to profile_path
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :gender, :birth_date, :street, :city, :country, :avatar)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user
  skip_before_action :verify_authenticity_token, only: [:new]

  def new
  end

  def create
    authenticate!(:by_password)
    original_request = session[:original_request]
    session.delete(:original_request)
    flash[:success] = 'You have been logged in successfully!'
    redirect_to original_request || root_path
  end

  def destroy
    current_user.granted_accesses.destroy_all
    logout
    flash[:success] = 'You have been logged out successfully!'
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      warden.set_user(@user)
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy, :regenerate_secrets]

  def index
    @websites = current_user.websites
  end

  def new
    @website = Website.new
  end

  def create
    @website = current_user.websites.build(website_params)
    if @website.save
      redirect_to websites_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @website.update_attributes(website_params)
      redirect_to website_path(@website)
    else
      render :edit
    end
  end

  def destroy
    @website.destroy
    redirect_to websites_path
  end

  def regenerate_secrets
    @website.regenerate_secrete_token
    redirect_to website_path(@website)
  end

  private

  def set_website
    @website = current_user.websites.find(params[:id])
  end

  def website_params
    params.require(:website).permit(:name, :domain_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Single login', root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to 'Websites', websites_path %></li>
        <li><%= link_to 'Profile', profile_path %></li>
        <li><p class="navbar-text"><%= current_user.email %></p></li>
        <% if current_user&.profile&.avatar? %>
          <li>
            <div class="user-header-icon" style="background-image: url(<%= current_user.profile.avatar.thumb.url %>)"></div>
          </li>
        <% end %>
        <li><%= link_to 'Logout', logout_path %></li>
      <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Sign up', new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <% flash.each do |key, message| %>
            <div class="alert alert-<%= key.to_s %>" role="alert">
              <%= message %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SingleLogin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header' %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">Main page</h1>
      </div>
    </div>
  </div>
</section>

app/views/profiles/_form.html.erb
<% if @profile.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p>Errors creating profile:</p>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_for @profile, url: profile_path, method: (params[:action] == 'edit' ? :put : :post) do |form| %>
    <div class="form-group">
      <%= form.label :first_name, 'First name' %>
      <%= form.text_field :first_name, class: 'form-control', placeholder: 'First name', required: true %>
    </div>
    <div class="form-group">
      <%= form.label :last_name, 'Last name' %>
      <%= form.text_field :last_name, class: 'form-control', placeholder: 'Last name', required: true %>
    </div>
    <div class="radio">
      <%= form.label :gender_male, class: 'radio-inline' do %>
        <%= form.radio_button :gender, 'male' %>
        Male
      <% end %>
      <%= form.label :gender_fmale, class: 'radio-inline' do %>
        <%= form.radio_button :gender, 'female' %>
        Female
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :birth_date, 'Date of birth' %>
      <%= form.date_field :birth_date, class: 'form-control', placeholder: 'yyyy-mm-dd', required: true %>
    </div>
    <div class="form-group">
      <%= form.label :avatar, 'User avatar' %>
      <%= form.file_field :avatar %>
      <%= form.hidden_field :avatar_cache %>
      <% if @profile.avatar? %>
          <p class="help-block">Currently uploaded image:</p>
          <%= image_tag @profile.avatar.thumb.url %>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :street, 'Street' %>
      <%= form.text_field :street, class: 'form-control', placeholder: 'Street', required: true %>
    </div>
    <div class="form-group">
      <%= form.label :city, 'City' %>
      <%= form.text_field :city, class: 'form-control', placeholder: 'City', required: true %>
    </div>
    <div class="form-group">
      <%= form.label :country, 'Country' %>
      <%= form.text_field :country, class: 'form-control', placeholder: 'Country', required: true %>
    </div>
    <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/profiles/edit.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">Edit Profile</h1>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/profiles/new.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">Create new Profile</h1>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/profiles/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">User profile</h1>
        <% if @profile %>
          <table class="table table-responsive">
            <tbody>
              <tr>
                <td>First name</td>
                <td><%= @profile.first_name %></td>
              </tr>
              <tr>
                <td>Last name</td>
                <td><%= @profile.last_name %></td>
              </tr>
              <tr>
                <td>Gender</td>
                <td><%= @profile.gender %></td>
              </tr>
              <tr>
                <td>Date of birth</td>
                <td><%= @profile.birth_date %></td>
              </tr>
              <tr>
                <td>Avatar</td>
                <td>
                  <% if @profile.avatar? %>
                    <%= image_tag @profile.avatar.thumb.url %>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td>Street</td>
                <td><%= @profile.street %></td>
              </tr>
              <tr>
                <td>City</td>
                <td><%= @profile.city %></td>
              </tr>
              <tr>
                <td>Country</td>
                <td><%= @profile.country %></td>
              </tr>
            </tbody>
          </table>
          <div class="text-center">
            <%= link_to 'Edit Profile', edit_profile_path, class: 'btn btn-primary pull-left' %>
            <%= link_to 'Delete Profile', profile_path, method: :delete, class: 'btn btn-danger pull-right', confirm: 'Are you sure?' %>
          </div>
        <% else %>
          <div class="text-center">
            <%= link_to 'Create Profile', new_profile_path, class: 'btn btn-lg btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Errors creating user:</p>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @user do |form| %>
  <div class="form-group">
    <%= form.label :email, 'Email' %>
    <%= form.text_field :email, class: 'form-control', placeholder: 'Email', required: true %>
  </div>
  <div class="form-group">
    <%= form.label :password, 'Password' %>
    <%= form.password_field :password, class: 'form-control', placeholder: 'Password', required: true %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation, 'Password confirmation' %>
    <%= form.password_field :password_confirmation, class: 'form-control', placeholder: 'Retype password', required: true %>
  </div>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">New user registration</h1>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/websites/_form.html.erb
<% if @website.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Errors creating user:</p>
    <ul>
      <% @website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @website do |form| %>
  <div class="form-group">
    <%= form.label :name, 'Site name' %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'My awesome web application', required: true %>
  </div>
  <div class="form-group">
    <%= form.label :domain_name, 'Domain name' %>
    <%= form.text_field :domain_name, class: 'form-control', placeholder: 'example.com', required: true %>
  </div>
  <%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/websites/edit.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">Edit Website data</h1>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/websites/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">User websites</h1>
        <% if @websites.any? %>
        <table class="table table-responsive">
          <th>Site name</th>
          <th>Domain name</th>
          <th>Action</th>
          <tbody>
          <% @websites.each do |site| %>
            <tr>
              <td><%= site.name %></td>
              <td><%= site.domain_name %></td>
              <td><%= link_to 'Show', website_path(site), class: 'btn btn-primary btn-xs' %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <% end %>
        <br>
        <div class="text-center">
          <%= link_to 'Add new website', new_website_path, class: 'btn btn-lg btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/websites/new.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">Add new Website</h1>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/websites/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <h1 class="text-center">Show Website data</h1>
        <% if @website %>
          <table class="table table-responsive">
            <tbody>
              <tr>
                <td>Site name</td>
                <td colspan="2"><%= @website.name %></td>
              </tr>
              <tr>
                <td>Domain name</td>
                <td colspan="2"><%= @website.domain_name %></td>
              </tr>
              <tr>
                <td>Secrete ID</td>
                <td colspan="2"><%= @website.secrete_id %></td>
              </tr>
              <tr>
                <td>Secrete Token</td>
                <td><%= @website.secrete_token %></td>
                <td><%= link_to 'Regenerate', secrets_path, class: 'btn btn-default btn-xs' %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to 'Edit', edit_website_path(@website), class: 'btn btn-primary pull-left' %>
          <%= link_to 'Delete', website_path(@website), method: :delete, class: 'btn btn-danger pull-right' %>
        <% end %>
      </div>
    </div>
  </div>
</section>